# wave 3 - serverless namespace
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    openshift.io/cluster-monitoring: "true"
