apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # wave 0 define namespace
  - namespace.yaml
  # wave 1 prep
  - subscription-authorino.yaml
  # wave 2 install operator  
  - operator-group.yaml
  - subscription-rhoai.yaml
