# wave 4 - serverless operator group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-serverless-
  namespace: openshift-serverless
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  upgradeStrategy: Default
