apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-terminal-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/red-hat-data-services/genaidemo25-gitops.git
    targetRevision: HEAD
    path: module-lightspeed/install-web-terminal
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
  revisionHistoryLimit: 3
