apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/red-hat-data-services/genaidemo25-gitops.git
    targetRevision: HEAD
    path: module-lightspeed/install-pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
  revisionHistoryLimit: 3
