apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  identityProviders:
  - name: admin-user
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret-admin-user
  - name: test-user
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret-test-user
