apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret-admin-user
  namespace: openshift-config
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
data:
  # admin-user:brno123
  htpasswd: YWRtaW4tdXNlcjokYXByMSQ4cHdYamJwTSRKZzVCejhiSzJ0a0Z4dnNwM1BxajYwCg==
---
apiVersion: v1
data:
  htpasswd: dGVzdC11c2VyOiQyeSQwNSQ0Z2VHUFpTLmw1SXh6Ykp3WlRiME11ZHFxaXdEblhhMmtZZXluSmhVcDFFSUF1WW82eGZ0Uwo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"htpasswd":"dGVzdC11c2VyOiQyeSQwNSQ0Z2VHUFpTLmw1SXh6Ykp3WlRiME11ZHFxaXdEblhhMmtZZXluSmhVcDFFSUF1WW82eGZ0Uwo="},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"argocd"},"name":"htpass-secret-test-user","namespace":"openshift-config"},"type":"Opaque"}
  labels:
    app.kubernetes.io/managed-by: argocd
  name: htpass-secret-test-user
  namespace: openshift-config
type: Opaque
