# Create model connection secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.connection.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    opendatahub.io/connection-type-ref: {{ .Values.connection.type }}
    openshift.io/description: {{ .Values.connection.description | quote }}
    openshift.io/display-name: {{ .Values.connection.displayName | quote }}
  labels:
    opendatahub.io/dashboard: "true"
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded dockerconfigjson for registry access
  .dockerconfigjson: {{ .Values.connection.dockerConfigJson }}
  # Base64 encoded access type and OCI host
  ACCESS_TYPE: {{ .Values.connection.accessType }}
  OCI_HOST: {{ .Values.connection.ociHost }}